chore: Update sonar project creation logic (#356)

diff --git a/charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml b/charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml
--- a/charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml
+++ b/charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml
@@ -95,14 +95,23 @@ spec:
       script: |
         set -e
 
-        PROJECT_EXISTS=$(curl -s -u ${SONAR_TOKEN}: "${SONAR_HOST_URL}/api/components/show?component=${SONAR_PROJECT_KEY}" | jq -r ".component.key")
+        SONAR_RESPONSE=$(curl -s -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/components/show?component=${SONAR_PROJECT_KEY}")
 
-        if [ "$PROJECT_EXISTS" == "null" ]; then
+        if [[ -z "$SONAR_RESPONSE" ]]; then
+          echo "Token isn't valid or not defined"
+          exit 1
+        fi
+
+        if echo "$SONAR_RESPONSE" | jq -e '.errors[0].msg' &>/dev/null; then
           default_branch=$(kubectl get codebase $SONAR_PROJECT_NAME -o jsonpath='{.spec.defaultBranch}')
           echo "Create project ${SONAR_PROJECT_KEY}"
           curl -X POST -u ${SONAR_TOKEN}: "${SONAR_HOST_URL}/api/projects/create?name=${SONAR_PROJECT_KEY}&project=${SONAR_PROJECT_KEY}&mainBranch=${default_branch}"
         else
-          echo "Project ${SONAR_PROJECT_KEY} already exists"
+          if echo "$SONAR_RESPONSE" | jq -e '.component.key' &>/dev/null; then
+            echo "Project \"$SONAR_PROJECT_KEY\" already exists"
+          else
+            echo "Unknown Response format"
+          fi
         fi
     - name: mvn-goals
       image: $(params.MAVEN_IMAGE)
